Updater, init.ini and more
efosamark/Uberhand-Overlay pull request #33
Opened 2023-11-05 11:56 UTC by i3sey

2023-11-05 20:34 UTC, efosamark approved these changes

2023-11-05 20:43 UTC, efosamark requested changes
conflicts

2023-11-06 05:42 UTC, i3sey reviewed
fixed (i hope)

2023-11-08 07:30 UTC, efosamark approved these changes

2023-11-08 12:38 UTC, merged